name: CI/CD

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test and Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: backtrace
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: backtrace/go.sum
          
      - name: Run Tests
        working-directory: backtrace
        run: go test ./... -coverprofile=coverage.txt
        
      - name: Create Auto Tag
        if: github.ref == 'refs/heads/main' && success()
        working-directory: backtrace
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          TAG="v0.0.4-$(date +'%Y%m%d%H%M%S')"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  release:
    name: Build and Release
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          path: backtrace
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: backtrace/go.sum
          
      - name: Clone NTrace-core
        run: |
          git clone --depth 1 https://github.com/nxtrace/NTrace-core.git
          mv NTrace-core ../NTrace-core
          
      - name: Download dependencies
        working-directory: backtrace
        run: |
          go mod download
          go mod tidy
          
      - name: Build
        working-directory: backtrace
        run: |
          mkdir -p dist
          LDFLAGS="-s -w -X main.version=${GITHUB_REF#refs/tags/} -X main.buildTime=$(date -u '+%Y-%m-%d %H:%M:%S')"
          # 确保编译时包含所有依赖
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="$LDFLAGS" -o dist/backtrace-linux-amd64 ./cmd/backtrace
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="$LDFLAGS" -o dist/backtrace-linux-arm64 ./cmd/backtrace
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="$LDFLAGS" -o dist/backtrace-darwin-amd64 ./cmd/backtrace
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="$LDFLAGS" -o dist/backtrace-darwin-arm64 ./cmd/backtrace
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="$LDFLAGS" -o dist/backtrace-windows-amd64.exe ./cmd/backtrace
        shell: /usr/bin/bash -e {0}
          
      - name: Generate checksums
        working-directory: backtrace
        run: |
          cd dist
          sha256sum * > checksums.txt
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: backtrace/dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Latest Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: backtrace/dist/*
          tag_name: latest
          name: Latest Build
          body: |
            Latest build from main branch
            Built on ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
